import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :etma_handler, EtmaHandlerWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client (if email functionality needed)
# config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: EtmaHandler.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration is done in config/runtime.exs
